name: jadeis
favicon: null
layout_spectrum: 0.01435194700025022
typography_spectrum: 0.3569778981618583
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8092051260173321
  lightness: 0.6860742073040456
  saturation: 0.7036887605208904
  rhythmicContrast: 0.43207583553157747
purpose: []
